<?php
#
# File generated by Dolibarr installer 3.1.1 on 2012-03-06 23:36:47
#
# Take a look at conf.php.example file for an example of conf.php file
# and explanations for all possibles parameters.
#
$dolibarr_main_url_root='http://localhost';
$dolibarr_main_document_root='D:/SkyDrive/Dropbox/Projetos/Kurt/cliente';
#$dolibarr_main_url_root_alt='http://wallner.eng.br/cliente/custom';
#$dolibarr_main_document_root_alt='/home/tescom/public_html/www.wallner.eng.br/cliente/custom';
$dolibarr_main_data_root='D:/SkyDrive/Dropbox/Projetos/Kurt/cliente/clientedata';
$dolibarr_main_db_host='localhost';
$dolibarr_main_db_port='';
$dolibarr_main_db_name='tescom_cliente';
//$dolibarr_main_db_user='tescom_cliente';
$dolibarr_main_db_user='root';
//$dolibarr_main_db_pass='1kSP03180a';
$dolibarr_main_db_pass='';
$dolibarr_main_db_type='mysqli';
$dolibarr_main_db_character_set='utf8';
$dolibarr_main_db_collation='utf8_general_ci';
$dolibarr_main_authentication='dolibarr';

# Specific settings
$dolibarr_main_prod='0';
$dolibarr_nocsrfcheck='0';
$dolibarr_main_force_https='0';
$dolibarr_main_cookie_cryptkey='f6kwuryawq1owmqikmydyruilogbf5j4';
$dolibarr_mailing_limit_sendbyweb='0';


$WEBSERVICES_KEY = "1";
?>